version: '3'

services:
  backend:
    build: .
    ports:
      - '${PORT}:${PORT}'
      - '${WEB_PORT}:${WEB_PORT}'
    depends_on:
      - database
    volumes:
      - ./data:/usr/src/kof-server/data
      - app:/usr/src/kof-server
    networks:
      - app
      - database

  database:
    image: mongo
    command: mongod --port ${MONGODB_PORT}
    ports:
      - '${MONGODB_PORT}:${MONGODB_PORT}'
    volumes:
      - database:/data/db
    networks:
      - database

volumes:
  app:
    driver: local
  database:
    driver: local

networks:
  app:
    driver: bridge
  database:
    driver: ipvlan
